server:
  ip: 192.168.1.200
  port: 8761
eureka:
  instance:
    # 服务注册中心实例主机名
    hostname: ${spring.application.name}
    prefer-ip-address: true
    # 实例信息，显示IP和端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetch-registry: false
    # 指定服务注册中心位置
    service-url:
      defaultZone: http://${server.ip}:${server.port}/eureka/
    healthcheck:
      enabled: true
  server:
    # 关闭自我保护
    enable-self-preservation: true
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 1000
spring:
  application:
    # 这是发布至注册中心的服务名，靠此服务名服务之间相互调用
    name: eureka-server
  # 开启eureka访问权限
  security:
    user:
      name: eureka
      password: eureka